### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by lllanlll** [nefe/redux-in-chinese#413]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/38312122/154225035-fa538a03-22f5-456f-87c4-5a3e1fe84654.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/38312122/154225060-30cdb195-b25d-4205-853e-9a2294b3f55f.png">
这里应该是data吧 看之前的issue说改了 应该是英文原版改了 中文文档还没改 redux循序渐进-异步逻辑与数据请求

**Comment by camsong** [comment]
fixed by https://github.com/nefe/redux-in-chinese/commit/80a613bbfbdfb8f0dfb933ec6b44af55ccacaf4e
