### ISSUE TITLE
Redux教程第三节实例代码github地址失效

### ISSUE THREAD

**Issue by Elylicery** [nefe/redux-in-chinese#427]
**问题原文**：http://cn.redux.js.org/tutorials/essentials/part-3-data-flow
**问题描述**：该文中“您还可以克隆Github上相同的仓库。在克隆之后，您可以使用 npm install 来安装依赖，并使用 npm start 来启动。

如果您想看到我们要构建的最终版本，您可以切换到tutorial-steps分支，或打开 CodeSandbox 中的最终版本。”
其中所指的“”克隆Github上相同的仓库“提供的链接地址失效

**Comment by camsong** [comment]
fixed
