### ISSUE TITLE
命令修改

### ISSUE THREAD

**Issue by mohaixiao** [nefe/redux-in-chinese#436]
[Redux 循序渐进](http://cn.redux.js.org/tutorials/essentials/part-3-data-flow#!)

[数据流基础](http://cn.redux.js.org/tutorials/essentials/part-3-data-flow)

您还可以[克隆Github上相同的仓库](https://github.com/reduxjs/redux-essentials-example-app)。在克隆之后，您可以使用 npm install 来安装依赖，并使用 npm start 来启动。这里是npm run start

**Comment by camsong** [comment]
npm start = npm run start
