### ISSUE TITLE
这里的是多余吗

### ISSUE THREAD

**Issue by Nasuke** [nefe/redux-in-chinese#480]
[启动项目](https://cn.redux.js.org/tutorials/typescript-quick-start#%E5%AE%9A%E4%B9%89-hooks-%E7%B1%BB%E5%9E%8B)

![Snipaste_2022-11-27_22-02-20](https://user-images.githubusercontent.com/78846539/204139510-4127733f-e766-494c-b617-8f298cbd0518.png)

**Comment by camsong** [comment]
Fixed by https://github.com/nefe/redux-in-chinese/pull/481
