### ISSUE TITLE
夜间模式字体颜色问题

### ISSUE THREAD

**Issue by XIwen-chuan** [nefe/redux-in-chinese#485]
![image](https://user-images.githubusercontent.com/88535122/211157209-4d5e0948-c95c-4034-83ed-2f36aab80d19.png)
![image](https://user-images.githubusercontent.com/88535122/211157212-83234046-58e3-4769-8af7-ec680a0c7391.png)

**Comment by blockmood** [comment]
#492

**Comment by camsong** [comment]
Really appreciate this,thanks.
