### ISSUE TITLE
链接不能正常显示

### ISSUE THREAD

**Issue by codycjy** [nefe/redux-in-chinese#488]
https://github.com/nefe/redux-in-chinese/blob/f3de91dedccb601cfc5c26a2d69e4b2bd4752d53/docs/tutorials/essentials/part-2-app-structure.md?plain=1#L578

链接无法正常显示 `.org`前多了一个空格
删去后正常
[一组自定义 hooks，允许你的 React 组件与 Redux store 交互](https://react-redux.js.org/api/hooks)

**Comment by camsong** [comment]
Thanks for reporting, fixed.
