### ISSUE TITLE
异步逻辑与数据请求页面，文字错误

### ISSUE THREAD

**Issue by wanglei1900** [nefe/redux-in-chinese#498]
https://cn.redux.js.org/tutorials/essentials/part-5-async-logic

典型的模式是在调用之前 dispatch 一个 "pending" 的 action，然后是包含数据的 “sucdess” 或包含错误的 “failure” action  =>
典型的模式是在调用之前 dispatch 一个 "pending" 的 action，然后是包含数据的 “success” 或包含错误的 “failure” action

**Comment by camsong** [comment]
thanks for bug report :)
