### ISSUE TITLE
文档错误：章节《为什么 Redux Toolkit 是如今使用 Redux 的方式》，里面有段代码错误

### ISSUE THREAD

**Issue by MrHzq** [nefe/redux-in-chinese#511]
文档地址：https://cn.redux.js.org/introduction/why-rtk-is-redux-today

问题描述：
<img width="1511" alt="image" src="https://github.com/nefe/redux-in-chinese/assets/24823464/87bb9b58-7301-456d-9c54-596a3e2323a0">

**Comment by jizai1125** [comment]
没问题的，concat 方法也能接受值
